# Generated by Django 2.2 on 2020-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='describe',
            field=models.TextField(blank=True, max_length=80, null=True, verbose_name='プロフィール'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='user_default.jpg', null=True, upload_to='profile'),
        ),
    ]
