# Generated by Django 2.2.9 on 2020-08-13 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notepad', '0003_add_star_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='query',
            new_name='question',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.BooleanField(default=0, verbose_name='復習')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='review',
            field=models.ManyToManyField(to='notepad.Review', verbose_name='復習'),
        ),
    ]
