# Generated by Django 2.2.9 on 2020-08-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0004_add_review_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notepad.Question', verbose_name='問題'),
            preserve_default=False,
        ),
    ]
