# nginx
FROM nginx

# version
LABEL version=0.2

# add default.conf
COPY ./templates /etc/nginx/templates

# port
EXPOSE 80 443

# set environ
RUN /bin/sh -c "envsubst '$$APP_DOMAIN' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf"
